# Generated by Django 4.2.27 on 2026-01-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_promotioncode_cart_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='promotion',
            new_name='promotion_code',
        ),
    ]
