# Generated by Django 4.2.27 on 2026-01-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_rename_promotion_cart_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.promotioncode'),
        ),
    ]
